# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'VirusTotal GitHub Action'
description: "GitHub Action to upload and scan files with VirusTotal"
author: 'crazy-max'
branding:
  color: 'red'
  icon: 'activity'

inputs:
  vt_api_key:
    description: 'The GitHub token used to create an authenticated client for GitHub API'
    required: true
  files:
    description: 'Newline-delimited list of path globs for asset files to upload for analysis'
    required: true
  vt_monitor:
    description: 'If enabled, files will be uploaded to VirusTotal Monitor endpoint'
    default: 'false'
    required: false
  monitor_path:
    description: 'A path relative to current monitor user root folder to upload files'
    default: '/'
    required: false
  update_release_body:
    description: 'If enabled, analysis link(s) will be appended to the release body'
    default: 'false'
    required: true
  github_token:
    description: 'The GitHub token used to create an authenticated client for GitHub API'
    default: ${{ github.token }}
    required: false

outputs:
  analysis:
    description: 'Analysis results formatted as asset=analysisURL (comma separated)'

runs:
  using: 'node12'
  main: 'dist/index.js'
